export const sampleData = [
    {
        "id":111489713,
        "source":"AUTO",
        "status":"AVAILABLE",
        "categoryName":"News",
        "categoryId":100271,
        "title":"Kronologi Cekcok Pimpinan KPK Nawawi Pomolango dan Putra Amien Rais di Pesawat Versi KPK",
        "publisher":"Kompas.com",
        "publisherId":"100014",
        "publisherImageCdnHash":"http://www.kompas.com/",
        "badgeText":"",
        "publishTimeUnix":1597412738000,
        "thumbnail":{
           "type":"IMAGE",
           "hash":"0hXBYyshuAB21kAC48_tV4Ol5WBAJXbBRuADZWczRuWVkeMkczXm9LWEhTCwoeY0AzCjFKDUAAHFwbNkNoDGBL",
           "quality":0
        },
        "url":{
           "hash":"JqnNqJ",
           "url":"https://today.line.me/id/article/Kronologi+Cekcok+Pimpinan+KPK+Nawawi+Pomolango+dan+Putra+Amien+Rais+di+Pesawat+Versi+KPK-JqnNqJ"
        },
        "type":0,
        "postId":"111489713"
     },
     {
        "id":111491258,
        "source":"AUTO",
        "status":"AVAILABLE",
        "categoryName":"News",
        "categoryId":100271,
        "title":" Polisi Tahan Dua Tersangka Perdagangan Orang Kapal Cina ",
        "publisher":"Tempo.co",
        "publisherId":"100023",
        "publisherImageCdnHash":"http://www.tempo.co/",
        "badgeText":"",
        "publishTimeUnix":1597413900000,
        "thumbnail":{
           "type":"IMAGE",
           "hash":"0hlrzJIfHHM11HMxoM1ktMCn1lMDJ0XyBeIwViQxddbWk9AXMDKVYoaGs0OG9rVHQDKQV4PWEzKGw4BXdZeVUr",
           "quality":0
        },
        "url":{
           "hash":"X8Ro6l",
           "url":"https://today.line.me/id/article/Polisi+Tahan+Dua+Tersangka+Perdagangan+Orang+Kapal+Cina-X8Ro6l"
        },
        "type":0,
        "postId":"111491258"
     }    
]